name: 'Better Slack Deployment Notifications'
description: 'Send real-time deployment notifications to Slack with progress updates'
author: 'andrewbrereton'

inputs:
  slack-bot-token:
    description: 'Slack bot OAuth token (xoxb-...)'
    required: true
  channel-id:
    description: 'Slack channel ID for notifications'
    required: true
  deployment-status:
    description: 'Deployment status: start, progress, success, failure'
    required: true
  message-timestamp:
    description: 'Message timestamp for updates (from start notification)'
    required: false
  step-name:
    description: 'Current deployment step name'
    required: false
    default: 'Deployment'
  environment:
    description: 'Deployment environment (production, staging, etc.)'
    required: false
    default: 'production'
  custom-message:
    description: 'Custom message to include in notification'
    required: false

outputs:
  message-timestamp:
    description: 'Slack message timestamp for subsequent updates'
    value: ${{ steps.slack-notification.outputs.message-timestamp }}
  message-url:
    description: 'Direct URL to the Slack message'
    value: ${{ steps.slack-notification.outputs.message-url }}

runs:
  using: 'composite'
  steps:
    - name: Execute notification
      id: slack-notification
      shell: bash
      run: ${{ github.action_path }}/scripts/notify.sh
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        CHANNEL_ID: ${{ inputs.channel-id }}
        DEPLOYMENT_STATUS: ${{ inputs.deployment-status }}
        MESSAGE_TS: ${{ inputs.message-timestamp }}
        STEP_NAME: ${{ inputs.step-name }}
        ENVIRONMENT: ${{ inputs.environment }}
        CUSTOM_MESSAGE: ${{ inputs.custom-message }}
        ACTION_PATH: ${{ github.action_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_WORKFLOW: ${{ github.workflow }}